version: '3.9'
services:
  frontend:
    container_name: frontend_app
    build:
      context: ./card-transfer
    image: moneytransferservice-frontend:latest
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend_app
    build:
      context: ./
    image: moneytransferservice-backend:latest
    ports:
      - 8080:8080
    restart: always
    volumes:
      - logs_app:/logs
volumes:
  logs_app: