version: '3.9'  
services:
    frontend: 
        build: 
            context: ./card-transfer
        container_name: frontend_app
        ports:
            - 3000:3000
        restart: always
        depends_on:
            - beckend
    beckend:
        build: 
            context: ./
        container_name: beckend_app
        ports:
            - 8080:8080
        restart: always
        volumes:
            - logs_app:/app/logs
volumes:
    logs_app: